version: '3.5'

services:
  postgres:
    restart: unless-stopped
    image: postgres:latest
    env_file: .env 
    volumes:
       - postgres:/data/postgres
    ports:
      - "5436:5432"
    networks:
      - tickets_network
  
  pgadmin:
    restart: unless-stopped
    image: dpage/pgadmin4:5.6
    env_file: .env
    links:
      - postgres
    ports:
        - 15432:80
    volumes:
        - pgadmin:/var/lib/pgadmin
    depends_on:
        - postgres
    networks:
      - tickets_network

volumes:
    postgres:
    pgadmin:

networks:
  tickets_network:
    driver: bridge